### ISSUE TITLE
Support for auth token revocation

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/gaia#150]
Some apps may build OAuth style API solutions. Currently, in doing so, access to the authToken means that whatever outside app is using the blockstack app's API will have access to that token for 4 months. The end user should have a way to either set the expiry timeframe or revoke the token. 

This is outside the association token concept. This is for the core authToken.

**Comment by hstove** [comment]
> The end user should have a way to either set the expiry timeframe

The [current authentication scheme](https://github.com/blockstack/gaia#v1-authentication-scheme) supports passing an `exp` into the signed JWT used. You can use this to make it expire.

Supporting revocation of an existing key would require some new features, and would require a Gaia hub to keep some state about current and revoked keys, which it does not do.

**Comment by hstove** [comment]
I would like to see revocation of tokens, though. Kanstack will have collaboration soon, and it uses scoped auth tokens to write to a shared bucket. However, there is still an issue when you want to 'remove' a shared collaborator. I have mechanisms to rotate a shared private key, but the old gaia token is still valid. You could rotate the scoped auth token, I suppose.

One way of managing state could be to store revoked tokens in the user's hub. This would require Gaia to read from some predetermined location in the hub in order to see if a token is revoked. That could work, but it'd make writes slower by adding a network request. I'm not sure that's the best solution. Requiring hubs to use a database to store state wouldn't work, because migrating to a different hub would require migrating the database as well.

In fact, I'm thinking of dropping the usage of a shared group hub, and instead using signatures and an indexer to do collaboration. That solves the issue of not having the ability to revoke tokens.

**Comment by kantai** [comment]
Something we can do (with the help of a stateful sidecar) is support something like a "bump" to revoke, where we keep a single nonce in the stateful sidecar, which all tokens must use. Then, to revoke tokens, the stateful sidecar could bump that nonce. This would revoke _all outstanding tokens_, but would probably be the simplest to reason about. (Revoking individual tokens isn't hard to implement on the server, but a UI would need to assist users in figuring out which auth tokens even exist).

**Comment by kantai** [comment]
### Supporting revocation

Roughly speaking, we want _something_ like the following properties for revocation.

1. Revocation on at least a _per-bucket_ basis. Something like "revoke all tokens for the entire gaia hub" doesn't work because of shared gaia hubs.
2. Revocation must be performable client-side, with the gaia bucket's private key.
3. (Probably) Revocation should not require too much server state. That means, this would probably need to be stored _using the driver itself_.

From the above, what this means is that the revocation should probably be "bump number to revoke" and each gaia _bucket_ tracks its own number. We can add an endpoint to perform the bump. Now, how do we keep track of each gaia buckets current revocation number?

In my mind, there's two options:

1. Add state to the Gaia server. This would mean connecting a Gaia hub to a database or storage system of some kind.
2. Use the Gaia driver to store the data. This would mean that the Gaia hub would have to perform a _driver read_ on roughly every write (though, this could be cached).

Both of these have some downsides. At the moment, I'm leaning towards option 2 (it's downsides are kind of already realized by the `list-files` command)

**Comment by jcnelson** [comment]
Putting (2) in the context of today's implementation, it's possible for the Gaia hub to simply maintain a write-through cache.  Only the first read or write to the bucket would incur the extra penalty; every subsequent bucket operation would be just as fast as it is today.

**Comment by hstove** [comment]
> every subsequent bucket operation would be just as fast as it is today.

I don't see how this is true - won't every read have to check this cache to see if the token is revoked?

**Comment by jcnelson** [comment]
Yes, but the nonce would be stored in RAM.  Granted, it would be a few microseconds slower on the write path to check the auth token against the in-RAM nonce, but this would not be noticeably slower.

**Comment by kantai** [comment]
> Yes, but I was thinking that the bucket-to-nonce cache would be stored entirely in RAM. Granted, it would be a few microseconds slower on the write path to check the auth token against the in-RAM nonce, but this would not be noticeably slower. I updated my comment to reflect this.

Yes, option 2 would definitely have a write-through cache for this data. This would be pretty negligible overhead (probably 100x faster than, e.g., the token validation in the first place).

**Comment by markmhx** [comment]
@jehunter5811 Curious as to whether you have an immediate use case for this in mind?

**Comment by jehunter5811** [comment]
@markmhx I wouldn't say *immediate* need, but an immediate use case yes. I've written an API for Graphite that can be used by literally any other app (blockstack or not) to integrate Graphite. So, the user of the other app could write files to their Graphite gaia hub from that other app or they could load Graphite files into that app. 

The problem is that once a user grants access to the other app, the authToken is permanent and not revokable. So, if that app started acting maliciously, the user could not revoke access. 

I have some alternative solutions I plan to deploy if this is going to be a longer-term project for Blockstack or if it doesn't sound feasible right now. Thus far the solutions above don't sound like they address my need (but I could very easily be misunderstand as I've been known to do before).

**Comment by hstove** [comment]
Yeah, I have a need for this too with the new Radiks. Collaborative apps that share storage tokens obviously need to be able to revoke tokens.

**Comment by jehunter5811** [comment]
Question for everyone here: 

Is it not possible to simply generate a new, valid authToken on each successful sign in while invalidating the prior token?

**Comment by kantai** [comment]
> Is it not possible to simply generate a new, valid authToken on each successful sign in while invalidating the prior token?

Yeah, it'd be possible in the above description -- basically you'd be able to 'bump' the minimum version number on auth tokens on login, and then generate a valid one. This would invalidate all previous auth tokens.

**Comment by jehunter5811** [comment]
Then I totally support that option. In reading through this whole thread, this all sounded like it would only work for people running custom hubs, though. Would this also apply to the default gaia hub?

**Comment by kantai** [comment]
> Then I totally support that option. In reading through this whole thread, this all sounded like it would only work for people running custom hubs, though. Would this also apply to the default gaia hub?

Yep, this would also apply to the default hub.

**Comment by jcnelson** [comment]
Spoke with @zone117x more about this.  I think we should be tracking invalidated auth tokens with timestamps.  In particular:

* Scoped auth tokens need to have a _creation date_ 
* The file `/${address}-auth` contains the _oldest valid timestamp_
* A scoped auth token is valid if it is (1) not expired, and (2) its creation date is newer than the date in `/${address}-auth`
* Invalidating a bucket's auth tokens is achieved by writing a newer date to `/${address}-auth`.

This is almost the same as having an explicit revocation counter, but I think it's safer in practice because if the Gaia hub somehow loses the `/${address}-auth` file, you can restore it simply by knowing the _approximate_ date at which you last revoked everything.  It also means that you can do an invalidation simply with one `POST` with the current UTC date -- you don't have to read the counter first.

**Comment by kantai** [comment]
Yep -- that makes @jcnelson, though I would add, that we want to do this for the validation of any kind of token, not just scoped ones.

**Comment by markmhx** [comment]
@zone117x Are you currently working on this? And do we want to complete it this new sprint?

**Comment by zone117x** [comment]
@markmhx Yes, I have a branch for this ready to PR once this prerequisite PR https://github.com/blockstack/gaia/pull/194 is merged. There a couple minor remaining issues to address from the review and should be good to go.
