### ISSUE TITLE
Prevent New Year POST failures with relative timestamp comparison for Gaia hub token invalidation

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/gaia#171]
I was in an authenticated sessions when POSTs to Gaia started failing. Per @jcnelson this is because the Gaia hub updated to 2019 and my auth sessions was set to 2018 still.

**Comment by jcnelson** [comment]
The Gaia hub uses UTC dates to verify that the auth token is valid for this year.  However, it uses the _absolute_ date, so every New Year's Eve we'll see a rolling failure depending on what the user's time zone is.  We need to switch the auth payload to include a UNIX timestamp, and verify on the Gaia hub that the current date is no more than 1 year later (or whatever delta we end up using).

**Comment by markmhx** [comment]
Is it correct then to understand this bug as still invalidating all user sessions established in 2018 as far as Gaia writes are concerned? And all users who want to write to Gaia in 2019 will have to re-authenticate to do so?

@jcnelson if we switch the auth payload, I presume that'd only help new sessions from encountering this going into 2020? Is there any way to hot fix the PBC hub now so that existing sessions aren't essentially broken given the switch into 2019?

**Comment by jcnelson** [comment]
> Is it correct then to understand this bug as still invalidating all user sessions established in 2018 as far as Gaia writes are concerned? And all users who want to write to Gaia in 2019 will have to re-authenticate to do so?

That is correct.

> @jcnelson if we switch the auth payload, I presume that'd only help new sessions from encountering this going into 2020?

Yes, this will happen again in 2020 if we don't fix it.

> Is there any way to hot fix the PBC hub now so that existing sessions aren't essentially broken given the switch into 2019?

I'm working on that right now.

**Comment by jcnelson** [comment]
https://github.com/blockstack/gaia/pull/172

**Comment by jcnelson** [comment]
Hotfix is now deployed to hub.blockstack.org.  Please let us know ASAP if the problem persists.

**Comment by jehunter5811** [comment]
Verified this fix in Graphite and Stealthy

**Comment by markmhx** [comment]
@jcnelson Thanks for pushing this hotfix yesterday. I'm assigning this issue to you and changing its title to reflect the remaining token invalidation change needed to prevent this from happening again in a year.

**Comment by markmhx** [comment]
Additionally, can you explain a bit why we have this 1-year invalidation in any case? And even with this fix, won't we find that users who have been authenticated for over a year will encounter POST failures and not realize the reason?

If so, I wonder if there's generally a better way to handle auth token invalidation from a UX perspective.

**Comment by kantai** [comment]
So, two things here.

1. We don't need to do this timestamping of the auth message at all anymore, since we now support the `exp` field in the authentication token. Historically, we used this to do rough (very very rough) expiration times on the authentication tokens.

2. Blockstack.js probably needs to do a better job to try and automatically handle the authentication failures (by, e.g., attempting to reauth) _OR_ we need to add instructions to our documentation and tutorials that tell developers that they should expect to handle auth failures in their code.

**Comment by markmhx** [comment]
Makes sense. So it sounds as though we should keep this issue open to address the first thing (by removing timestamping entirely) and we should spin up a new issue in a different repo to address the second thing.

Without thinking it through much, my gut tells me that automatically handling reauth, etc. with blockstack.js might be a complicated. And while we may want to evolve to handling failures automatically, we might as well start with better expectation setting in the docs (perhaps with clear guidance on the possible auth failures to expect)?

**Comment by markmhx** [comment]
https://github.com/blockstack/gaia/pull/173
