### ISSUE TITLE
Set up automated testing for docker compose

### ISSUE THREAD

**Issue by markmhx** [blockstack/gaia#184]

**Comment by GInxh** [comment]
In addition to the normal gaia hub testing, an additional test would be created to be automated to test all the API endpoints and edge cases designed we would like to test for localhost and images. The integration or implementation of this test can be separate from the other testing, but will be up for review.

**Comment by GInxh** [comment]
Edge cases to consider

* API call for setting disk and associated credentials for cloud buckets (like S3) will cause the hub container on the localhost version on the image to fail due to a disk setting overwrite. 

Ideally, noone should be configuring these settings on the image, but it should be available for branching of the docker-compose version for people to configure how they like. 

Thus, a particular configuration specific to the images should be set in place to block any disk driver setting besides "disk" but allow credentials in case third party cloud host providers or individuals utilise third party attestations for local disk storage (like the new sgx enclaves security settings released by intel) for writes authing through an sgx enclave or otherwise. 

* Same for port settings. docker-compose should be allowed for advanced users to define but set in the image.
