### ISSUE TITLE
Edit gaia hub drivers to check content-size on gaia hub writes 

### ISSUE THREAD

**Issue by GInxh** [blockstack/gaia#187]
chunks the upload progress for size monitoring.

**Comment by markmhx** [comment]
@GInxh Does this issue pertain to the containers epic?

**Comment by GInxh** [comment]
This effects production and develop branch, and also what I am working on for containerizing the develop branch.

**Comment by GInxh** [comment]
@markmhx not apart of the epic since if effects master and develop branch and not just the http feature/docker-compose branch

**Comment by markmhx** [comment]
@GInxh Is this issue strictly necessary to fulfill that epic even if it affects those other branches? 

If not, then I agree let's remove from the epic. But if so, I think it'd be good to include it.

**Comment by kantai** [comment]
We've generally recommended enforcing something like this via a reverse proxy (e.g.) nginx. The advantage of doing that is that it ensures we don't create an extra in memory copy of the request body (which can be quite easy to do accidently).

If we wanted to add this functionality to the hub itself, we'd probably not want to do this via the drivers, because this functionality would apply to all of the drivers, and doesn't really depend on any driver-specific issues. We could add it to the handler in `hub/src/server/http.js` or `server.js`. The tricky bit is ensuring that you don't ever buffer the request's body. There's an express middleware class that could handle this pretty easily -- `body-parser`, but it buffers the request body. What we'd want is something that simply places a limit on the amount of data that can read out of a given stream.

**Comment by zone117x** [comment]
This article has some good info on avoiding those types of problems https://nodejs.org/en/docs/guides/backpressuring-in-streams/#lifecycle-of-pipe
Looks like staying within the `pipe` API is key. The entire body can avoid being copied, but I think size enforcement requires monitoring chunks and those probably are copied/GC'd.

**Comment by zone117x** [comment]
After some more experience with our driver implementations and the Nodejs stream/pipe API, this is really easy to implement and get right. It doesn't need implemented per driver, just one spot, and probably just using the [stream.PassThrough](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) to count chunk bytes and `.destroy()` the stream when limit is exceeded.

**Comment by timstackblock** [comment]
Tested as part of https://github.com/blockstack/gaia/pull/256

**Comment by ghost** [comment]
@markmhendrickson 

I will be deleting my github and per github policy all code & comments in repositories I do not own will remain (production will not be impacted) and replaced with github general ghostuser account https://github.com/ghost

Please edit your comments to remove the "@myusername" here as other peoples mentions of my username, which I want deleted. 

When the "@myusername" is appropriately removed, I will also remove this comment.

All comments that do not mention my username explicitly are to remain UNEDITED by me per the open source archive standards, but all comments mentioning my username are not necessary in the comments for open source development so deleting them will not be an issue.

Thank you!
